### ISSUE TITLE
don't store db host and pass in yaml, just have it in .env

### ISSUE THREAD

**Issue by jbartus** [lamp-io/lio#108]

**Comment by jbartus** [comment]
for example:
```
laravel new app_foo
cd app_foo
lio deploy --laravel --no-interaction
```
- use a tmp file or in-memory, do not manipulate users local `.env` file
- take the password string returned from the create database, use it to populate the `DB_PASSWORD=` line in the tmp/in-mem `.env` and PATCH it to the app's remote `.env`
- only do this if the user is creating a new db during this deploy
- take out the part where it tries to create/manage mysql users for you

**Comment by KirillPerepelitsa** [comment]
All points done
Now .env file will be placed to shared folder, on a first deploy, 
Inside of release folder placed symlink pointed to shared/.env
