### ISSUE TITLE
put lio in my path somehow

### ISSUE THREAD

**Issue by jbartus** [lamp-io/lio#11]
so you could do something like:
```
$ composer install -g lamp-io/lio
$ lio auth
```

**Comment by KirillPerepelitsa** [comment]
Hi, 

after will be applied this pull request https://github.com/lamp-io/lio/pull/17 

You will need to create package in composer package registry, here the link https://packagist.org/ (you  just need to create acc and link your github repo to your new package) 

Then you should be able to use `composer global install lamp-io/lio` 

For tests i've created copy of  your git repo and created package from it, `composer global require kirill-perepelitsa/lio`

And you will be able to use $lio auth/{any other implemented command} 

Troubleshooting: 
1) Make sure that your home composer bin directory presented in your PATH (usually it will be $HOME/.composer/vendor/bin or $HOME/.config/.composer/vendor/bin on unix, on Windows it should be C:\\Users\USERNAME\AppData\Roaming\Composer\vendor\bin)

2) If installation will fail,   update in your global composer.json (it will be placed in .composer/composer.json dir), minimum-stability field, to `dev` from `stalbe` (this hot fix will be required till we dont make release stable version in github repository)
 {
    "minimum-stability": "dev" 
}

**Comment by jbartus** [comment]
it worked!
```
root@arbit:~# composer global require lamp-io/lio
Changed current directory to /root/.config/composer
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Using version dev-master for lamp-io/lio
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Installing art4/json-api-client (0.10): Loading from cache
  - Installing lamp-io/lio (dev-master 240d218): Cloning 240d2188b0 from cache
Writing lock file
Generating autoload files
root@arbit:~# lio
Console Tool

Usage:
  command [options] [arguments]

Options:
  -h, --help            Display this help message
  -q, --quiet           Do not output any message
  -V, --version         Display this application version
      --ansi            Force ANSI output
      --no-ansi         Disable ANSI output
  -n, --no-interaction  Do not ask any interactive question
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Available commands:
  auth           Set auth token
  help           Displays help for a command
  list           Lists commands
 apps
  apps:describe  gets the apps you specify
  apps:list      gets the set of apps from the org associated with your token
  apps:new       Creates a new app
 files
  files:list     Return files from the root of an app
```
