### ISSUE TITLE
Append description autodeploy:<repoName>:<branch>

### ISSUE THREAD

**Issue by KirillPerepelitsa** [lamp-io/lio#116]
For deploy from CI/CD, append autodeploy:<repoName>:<branch> to description

**Comment by JeremyChase** [comment]
* multi-deploy only in CI/CD
* `deploy-branches` config option, array of branch names to auto-deploy
* `deploy-all-branches` boolean config option to deploy any branch pushed
* deleted branches must have apps deleted (see if you can do it, otherwise report back)

**Comment by KirillPerepelitsa** [comment]
Setup: Clone branch with changes, create alias for it (lio_test to not conflict with global package installation) install laravel  
```shell  git clone --single-branch --branch deploy_fixes  https://github.com/lamp-io/lio.git && 
cd lio && 
composer install &&
cd ../ &&
alias lio_test=$PWD"/lio/bin/lio" &&
laravel new app_foo && cd app_foo
```
Test cases:

1. Check that autodeploy working for master without any settings, and user dont need to specify app_id anywhere
```shell
export CI="true"
export GIT_BRANCH="master" &&
lio deploy --laravel -n &&
lio deploy --laravel -n
```
Expected result: 1 working laravel app with 2 releases

  2.  Check that autodeploy will not works for any branch until it will be specified on a config file
```shell
export CI="true"
export GIT_BRANCH="foo" &&
rm lamp.io.yaml && 
lio deploy --laravel -n
```
Expected result: Exception:  Branch foo not allowed for auto-deploy. Command status code 1

3. Check that adding setting deploy-branches: - foo, will allow to make autodeploys from this branch
```shell
export CI="true"
export GIT_BRANCH="foo" &&
rm lamp.io.yaml &&
echo  "deploy-branches:\\n  - foo" > lamp.io.yaml &&
lio deploy --laravel -n
```
Expected result: Working laravel app (on app description you will see branch name `foo`)

4. Check that autodeploy will works only for specified in config file branches
```shell
export CI="true"
export GIT_BRANCH="foobar" &&
rm lamp.io.yaml &&
echo  "deploy-branches:\\n  - foo" > lamp.io.yaml &&
lio deploy --laravel -n
```
Expected result: Exception:  Branch foobar not allowed for auto-deploy. Command status code 1

5. Check that setting deploy-all-branches: true, will allow to make deploys from any branches
```shell
export CI="true"
export GIT_BRANCH="foobar" &&
rm lamp.io.yaml &&
echo  "deploy-all-branches: true" > lamp.io.yaml &&
lio deploy --laravel -n
```

Expected result: Exception: Working laravel app, (on app description you will see branch name `foobar`)

**Comment by KirillPerepelitsa** [comment]
Its already merged, but can be tested, only after fix issue with symlinks
