### ISSUE TITLE
`lio deploy` does not accept `-y`

### ISSUE THREAD

**Issue by JeremyChase** [lamp-io/lio#133]

**Comment by KirillPerepelitsa** [comment]
@JeremyChase 
If you need no interaction mode (where all questions will be answered with default values)
you need to use [-n][--no-interaction] option

The reasons why i've added [-y][--yes] option for delete commands, as we decided to set default answer for this question NO, so [-n] option will not help in such cases

**Comment by JeremyChase** [comment]
Ah - thanks.
