### ISSUE TITLE
apps:new don't pass parameters

### ISSUE THREAD

**Issue by JeremyChase** [lamp-io/lio#16]
Can be reproduced by:

`bin/console apps:new -d foo <orgid>`

The description will not be set.

**Comment by KirillPerepelitsa** [comment]
Hi @JeremyChase , i've faced issue today, that i cant create any application without my credit card (sign in from different g-mail account wasn't help too). Am i able somehow to create some sort of trial acc?

**Comment by JeremyChase** [comment]
@KirillPerepelitsa Yes, there are additional promo codes to extend the free trial for development purposes. I'll send them out of band.
