### ISSUE TITLE
lio hangs on missing token

### ISSUE THREAD

**Issue by jbartus** [lamp-io/lio#160]
if lio doesn't detect a token where it expects one it prompts the user to input one

this prompt never times out, so the effect is to "hang" any script where a token is missing (invalid tokens will error out as expected).  this is true even with `-q`

for scripts this seems like the wrong default behavior.  especially ci/cd setups.  for first time console users maybe its not.  i'm not sure where to go with this so just noting it for future discussion.

**Comment by KirillPerepelitsa** [comment]
@jbartus As the idea, we can allow to set token via env var, it should resolve this problem

As e.g, lio will check token in ENV ($LAMP_IO_TOKEN), if it empty then it will try to read it from file, if it empty as well it will ask user to prompt token

**Comment by jbartus** [comment]
lio should simply exit with a clear error message on a missing or invalid token, not prompt to supply one

**Comment by jbartus** [comment]
yes to env var
