### ISSUE TITLE
If lio is installed to an app an exported LAMP_IO_TOKEN does not work

### ISSUE THREAD

**Issue by JeremyChase** [lamp-io/lio#173]
Steps to reproduce:
* Install composer via [this](https://www.lamp.io/docs/how-to-deploy-laravel-in-the-cloud)
* Install lio by running `composer require lamp-io/lio`

```
export LAMP_IO_TOKEN=<token>; vendor/bin/lio
```
Results in this output:
```
Tokens can be generated at https://www.lamp.io/tokens

Enter token:


Aborted.
```

**Comment by KirillPerepelitsa** [comment]
Version missmatch, `composer require lamp-io/lio` will install the latest release (its 0.1.1) that i've created some time ago, when i made a showcase how works automatic release creation with travis
And this release doesnt contain feature with storing token in a env var

This snippet will install via composer latest lio version 
`rm -rf * \
#Without empty composer.json file composer throw me an error
&& echo {} > composer.json \
&& curl -so /tmp/composer.phar https://getcomposer.org/composer.phar \
&& php /tmp/composer.phar config minimum-stability dev \
&& php /tmp/composer.phar require lamp-io/lio:dev-master`
And then you can run `export LAMP_IO_TOKEN=<TOKEN> && vendor/bin/lio apps:list`

**Comment by KirillPerepelitsa** [comment]
https://github.com/lamp-io/lio/releases/tag/0.1.2

Release 0.1.2 has been created, so no version missmatch anymore
