### ISSUE TITLE
databases:update error on missing arguments

### ISSUE THREAD

**Issue by jbartus** [lamp-io/lio#51]
right now you get this
```
root@arbit:~/github.com/lamp-io/lio# ./bin/lio databases:update db-qgb5c
Client error: `PATCH https://api.lamp.io/databases/db-qgb5c` resulted in a `400 Bad Request` response:
{"errors":[{"detail":"json: cannot unmarshal array into Go struct field Node.attributes of type map[string]interface {}" (truncated...)
```
~there should be a way to send a changeless-patch (basically a json body with zero attributes) such that it still gets the PATCH but doesn't return an error.~

**Comment by jbartus** [comment]
also i'm open to the notion that we either don't want the cli doing dry-patches or we want to prompt the user to confirm y/n, like
`An update with no changes will restart your database, are you sure? (Y/n)`

**Comment by jbartus** [comment]
i was wrong, only an explicit status attribute set to 'restarting' will trigger a restart.  a dry patch is basically pointless, so it should prompt the user to supply at least one argument/option and show them the list.

**Comment by JeremyChase** [comment]
> a dry patch is basically pointless

It isn't pointless. I perform 'dry patches' after many kube updates.

**Comment by jbartus** [comment]
I can't tell if you're arguing for the sake of abstract rightness or making a point about what you want the spec or behavior to be.
