### ISSUE TITLE
databases:new doesn't account for password

### ISSUE THREAD

**Issue by jbartus** [lamp-io/lio#53]
when you create a new db without a password argument you get a database you cant login to
```
root@arbit:~/github.com/lamp-io/lio# ./bin/lio databases:new
+----------+----------------------+------------------------------- Database -+-----------------+-----+---------+----------------------+------+
| Id       | created_at           | created_by_user_id              | memory | organization_id | ssd | status  | updated_at           | vcpu |
+----------+----------------------+---------------------------------+--------+-----------------+-----+---------+----------------------+------+
| db-akkzk | 2019-07-26T13:13:20Z | user-rpxg4xef6var5okxxkq2xbgdo4 | 512Mi  | org-3tnjm       | 1Gi | pending | 2019-07-26T13:13:20Z | 0.25 |
+----------+----------------------+---------------------------------+--------+-----------------+-----+---------+----------------------+------+
```
in the web user interface we handle this with a modal that looks like this:
![dbpassmodal](https://user-images.githubusercontent.com/561971/61953978-bf822780-af85-11e9-85db-3d189b9a23a8.png)

i'm genuinely unsure of how best to tackle this, so just creating a ticket for tracking.  ideas/research welcome.

**Comment by jbartus** [comment]
couple more tweaks:
- can you change the wording to `Please provide a password for the MySQL root user (leave blank for a randomly generated one): `
- then if they do leave it blank, do the POST but display a warning after the results, something like `Warning: This is the last chance to copy the mysql root password, we do not keep it.`
- if they provide a password *don't* display it in the response/output.  they know what it was.
- when you type a password it would be nice if you got `******` characters to show you something was happening

**Comment by jbartus** [comment]
Oh and I agree w/Jeremy I think we went overboard on the password restrictions.    When we auto-generate them they should be at least that "good", but if a user wants to enter something less than that it can be fine too.   Lets make it:
- at least 8 chars
- at least one number or symbol

**Comment by JeremyChase** [comment]
@KirillPerepelitsa There is no need to randomly generate a passsword. If no password is supplied the api will randomly generate one itself.

**Comment by jbartus** [comment]
^ yea kirill i was wrong about that in chat last night

**Comment by KirillPerepelitsa** [comment]
Ye, but i've added it only for databases:update 

When you updating with empty value `{"mysql_root_password": ""}` it just nullify your password. So in that case i am generating this random value.

On databases:new command i am not using password generation on client side

**Comment by JeremyChase** [comment]
@KirillPerepelitsa  Please see my [review](https://github.com/lamp-io/lio/pull/57#pullrequestreview-268480877) in #57

**Comment by JeremyChase** [comment]
If `--mysql_root_password` is supplied we want to prompt with:
 
 `Enter MySQL root password: `

If `""` is entered, exit with a non-zero status code with a messaging saying `"Error: Refusing to set empty password"`

**Comment by JeremyChase** [comment]
Other than checking for the empty string there should be no code related to password length or complexity.
