### ISSUE TITLE
logs:list default output

### ISSUE THREAD

**Issue by jbartus** [lamp-io/lio#59]
for `lio logs:list` the table returned should be three columns:
`timestamp | pod_name | payload`, sorted by timestamp with the most recent log line last (at the bottom).

please don't group the lines by pod

**Comment by jbartus** [comment]
thank you!

**Comment by JeremyChase** [comment]
@jbartus Did you test this? It doesn't seem to be displaying any logs for me.

**Comment by KirillPerepelitsa** [comment]
@JeremyChase do you have some fresh logs on db/apps pods ? 

By default it shows logs only for last 10 minutes
