### ISSUE TITLE
deploy --laravel fixes

### ISSUE THREAD

**Issue by KirillPerepelitsa** [lamp-io/lio#75]
1. Fix .env on client side after deploy
2. handle cases when app_runs status failed 
3. make revert of whole process, if command failed 
4. add ckecking is_app exists, and is_db_exists
5. db dump import option (in config, database: sql_dump: {path_to_dump})
6. releases/release_1565211805 just be releases/date(YYYYMMDDHHMMSS)
7. exception if app not found on directory
8. fix storage accessibility
8. Share storage folder between all releases
9. check is first deploy (even if app_id specified in config, need to check does it have releases folder)
10. check case when exception in createSymlinkStorage(), why revert goes wrong
11. rnd how to switch between deploys
12. allow user to run commands before finish deploy (artisan commands) need to add to config files  commands: - {command_name} 
13. run all mysql staff not as a root user

**Comment by KirillPerepelitsa** [comment]
1) Fix .env on client side after deploy 
2) handle cases when app_runs status failed

**Comment by KirillPerepelitsa** [comment]
All points were done, except of 12, wanted to discuss this point on meeting

**Comment by JeremyChase** [comment]
Kirill - Please go through issues and verify. Close if you are satisfied.
